name: "Get next release version"
description: "Determines the next release version for this repository"
inputs:
  branch:
    description: "The release branch to use"
    default: "saga"
    required: false
  githubRepository:
    description: "The GitHub repository, format: user/repository"
    required: true
  defaultVersion:
    description:
      "The default version to use in case no new release is determined"
    required: false
    default: "0.0.0-development"
outputs:
  nextRelease:
    description: "The next release version"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.githubRepository }}
    - ${{ inputs.branch }}
    - ${{ inputs.defaultVersion }}
