manifest:
  remotes:
    - name: nordic
      url-base: https://github.com/NordicPlayground
  projects:
    - name: fw-nrfconnect-nrf
      path: nrf
      remote: nordic
      revision: 7c8d3e1237a9a7fe9aa09d99369cfcf243817b4d
      import: true
  self:
    path: firmware
