name: Test and Release

on: push

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  tests:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Keep npm cache around to speed up installs
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci --no-audit
      - run: npx tsc
      - run: docker build ./
      - name: Semantic release
        continue-on-error: true
        run: npx semantic-release
