name: Example

on: push

jobs:
  version:
    name: Determine next release version
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4

      - name: Determine next release version
        uses: nordicsemiconductor/cloud-get-next-version-action@saga
        id: version
        with:
          branch: saga

      - run: |
          NEXT_VERSION=${{ steps.version.outputs.nextRelease }}
          echo ${NEXT_VERSION}
