name: Example

on: push

jobs:
  version:
    name: Determine next release version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Determine next release version
        uses: bifravst/get-next-version-action@saga
        id: version
        with:
          branch: saga

      - run: |
          NEXT_VERSION=${{ steps.version.outputs.nextRelease }}
          echo ${NEXT_VERSION}
